apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-claim
  namespace: homepage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi

