apiVersion: v1
kind: Service
metadata:
  labels:
    app: homepage
  name: homepage
  namespace: homepage
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: homepage
  type: LoadBalancer
