apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
        - mountPath: /app/data
          name: persist
    - image: busybox
      name: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
        - mountPath: /persist
          name: persistent-volume
  volumes:
    - name: persist
      persistentVolumeClaim:
        claimName: persist
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi
    - name: persistent-volume
      hostPath:
        path: /tmp/rancher-volumes
        type: DirectoryOrCreate
