apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
  name: gitlab
  namespace: gitlab
spec:
  ports:
    - name: ui
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: gitlab
  type: LoadBalancer
